---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    volumes:
      - ./config:/config
      - /mnt/external-hdd/shared/media/Series:/tv #optional
      - /mnt/external-hdd/shared/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

