version: "3.9"

services:
  qbittorrent-nox:
    container_name: qbittorrent-nox
    environment:
      - PGID=1000
      - PUID=1000
      - QBT_EULA=accept
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=8080
      - TZ=Europe/Belgrade
    image: qbittorrentofficial/qbittorrent-nox:latest
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8080:8080/tcp
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ./config:/config
      - /mnt/external-hdd/shared/downloads:/downloads
