---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    volumes:
      - ./config:/config
      - /mnt/external-hdd/shared/media/Movies:/movies #optional
      - /mnt/external-hdd/shared/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
