---
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    volumes:
      - ./config:/config
      - /mnt/external-hdd/shared/media/Movies:/movies #optional
      - /mnt/external-hdd/shared/media/Series:/tv #optional
    networks:
      - pihole-unbound_default
    dns:
      - 172.19.0.1
    ports:
      - 6767:6767
    restart: unless-stopped
networks:
  pihole-unbound_default:
    external: true
