---
version: "2.1"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Belgrade
    networks:
      - pihole-unbound_default     
    dns:
      - 172.19.0.1
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
networks:
  pihole-unbound_default:
    external: true
